services:
  user:
    image: user-app:latest
    restart: unless-stopped
    container_name: user-app
    ports: 
      - 8080:8080
    env_file:
      - user/.env
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app-network
  jam:
    image: jam-app:latest
    restart: unless-stopped
    container_name: jam-app
    ports: 
      - 8081:8081
    env_file:
      - jam/.env
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app-network
  battle:
    image: battle-app:latest
    restart: unless-stopped
    container_name: battle-app
    ports: 
      - 8082:8082
    env_file:
      - battle/.env
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app-network
  gradebook:
    image: gradebook-app:latest
    restart: unless-stopped
    container_name: gradebook-app
    ports: 
      - 8083:8083
    env_file:
      - gradebook/.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
  mysqldb:
    image: 'mysql:8'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306
    volumes:
      - './database/mysql/init:/docker-entrypoint-initdb.d'
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  mongodb:
    image: 'mongo:7.0'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./database/mongodb/init:/docker-entrypoint-initdb.d
      - mongodb_data:/var/lib/mongodb
    networks:
      - app-network
  broker:
    image: apache/kafka:4.2.1
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local