// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package graph

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type UserGraphQLClient interface {
	GetUser(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) UserGraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetUser_User struct {
	ID    string       "json:\"id\" graphql:\"id\""
	Level *DancerLevel "json:\"level,omitempty\" graphql:\"level\""
	Role  UserRole     "json:\"role\" graphql:\"role\""
}

func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetLevel() *DancerLevel {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Level
}
func (t *GetUser_User) GetRole() *UserRole {
	if t == nil {
		t = &GetUser_User{}
	}
	return &t.Role
}

type GetUser struct {
	User *GetUser_User "json:\"user,omitempty\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return t.User
}

const GetUserDocument = `query GetUser ($userId: ID!) {
	user(id: $userId) {
		id
		level
		role
	}
}
`

func (c *Client) GetUser(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"userId": userID,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument: "GetUser",
}
