// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateUserInput struct {
	Name  string       `json:"name"`
	Email string       `json:"email"`
	Level *DancerLevel `json:"level,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Level     *DancerLevel `json:"level,omitempty"`
	CreatedAt string       `json:"createdAt"`
}

type DancerLevel string

const (
	DancerLevelBeginner DancerLevel = "beginner"
	DancerLevelAmateur  DancerLevel = "amateur"
	DancerLevelPro      DancerLevel = "pro"
)

var AllDancerLevel = []DancerLevel{
	DancerLevelBeginner,
	DancerLevelAmateur,
	DancerLevelPro,
}

func (e DancerLevel) IsValid() bool {
	switch e {
	case DancerLevelBeginner, DancerLevelAmateur, DancerLevelPro:
		return true
	}
	return false
}

func (e DancerLevel) String() string {
	return string(e)
}

func (e *DancerLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DancerLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DancerLevel", str)
	}
	return nil
}

func (e DancerLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DancerLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DancerLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleDancer    UserRole = "dancer"
	UserRoleJudge     UserRole = "judge"
	UserRoleMedia     UserRole = "media"
	UserRoleOrganizer UserRole = "organizer"
)

var AllUserRole = []UserRole{
	UserRoleDancer,
	UserRoleJudge,
	UserRoleMedia,
	UserRoleOrganizer,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleDancer, UserRoleJudge, UserRoleMedia, UserRoleOrganizer:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
