SET time_zone = '+00:00';

CREATE DATABASE IF NOT EXISTS battledb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'battle_app'@'%' IDENTIFIED BY '${DB_BATTLE_APP_PASSWORD}';

GRANT ALL ON battledb.* TO 'battle_app'@'%';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS battle (
    id VARCHAR(36) PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL,
    dancer1 VARCHAR(255) NOT NULL,
    dancer2 VARCHAR(255) NOT NULL,
    winner_id VARCHAR(36) DEFAULT NULL,
    status ENUM('pending', 'in_progress', 'finished') NOT NULL DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS judge_score (
    battle_id VARCHAR(36) NOT NULL,
    judge_id VARCHAR(36) NOT NULL,
    dancer1_score INT NOT NULL,
    dancer2_score INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (battle_id, judge_id),
    
    FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;