// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BattleStatus.
const (
	BattleStatusFinished   BattleStatus = "finished"
	BattleStatusInProgress BattleStatus = "in_progress"
	BattleStatusPending    BattleStatus = "pending"
)

// Valid indicates whether the value is a known member of the BattleStatus enum.
func (e BattleStatus) Valid() bool {
	switch e {
	case BattleStatusFinished:
		return true
	case BattleStatusInProgress:
		return true
	case BattleStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for BattleResultStatus.
const (
	BattleResultStatusFinished BattleResultStatus = "finished"
)

// Valid indicates whether the value is a known member of the BattleResultStatus enum.
func (e BattleResultStatus) Valid() bool {
	switch e {
	case BattleResultStatusFinished:
		return true
	default:
		return false
	}
}

// Battle defines model for Battle.
type Battle struct {
	Dancer1Id *string       `json:"dancer1_id,omitempty"`
	Dancer2Id *string       `json:"dancer2_id,omitempty"`
	EventId   *string       `json:"event_id,omitempty"`
	Id        *string       `json:"id,omitempty"`
	Status    *BattleStatus `json:"status,omitempty"`
	WinnerId  *string       `json:"winner_id,omitempty"`
}

// BattleStatus defines model for Battle.Status.
type BattleStatus string

// BattleResult defines model for BattleResult.
type BattleResult struct {
	BattleId          *string             `json:"battle_id,omitempty"`
	Dancer1TotalScore *int                `json:"dancer1_total_score,omitempty"`
	Dancer2TotalScore *int                `json:"dancer2_total_score,omitempty"`
	FinishedAt        *time.Time          `json:"finished_at,omitempty"`
	Status            *BattleResultStatus `json:"status,omitempty"`
	WinnerId          *string             `json:"winner_id,omitempty"`
}

// BattleResultStatus defines model for BattleResult.Status.
type BattleResultStatus string

// Error defines model for Error.
type Error struct {
	// Error error text description
	Error string `json:"error"`
}

// CreateBattleJSONBody defines parameters for CreateBattle.
type CreateBattleJSONBody struct {
	Dancer1Id string `json:"dancer1_id"`
	Dancer2Id string `json:"dancer2_id"`
	EventId   string `json:"event_id"`
}

// SubmitScoresJSONBody defines parameters for SubmitScores.
type SubmitScoresJSONBody struct {
	Dancer1Score int    `json:"dancer1_score"`
	Dancer2Score int    `json:"dancer2_score"`
	JudgeId      string `json:"judge_id"`
}

// CreateBattleJSONRequestBody defines body for CreateBattle for application/json ContentType.
type CreateBattleJSONRequestBody CreateBattleJSONBody

// SubmitScoresJSONRequestBody defines body for SubmitScores for application/json ContentType.
type SubmitScoresJSONRequestBody SubmitScoresJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create battle
	// (POST /battles)
	CreateBattle(c *gin.Context)
	// Finish battle
	// (POST /battles/{id}/finish)
	FinishBattle(c *gin.Context, id string)
	// Judge submit score
	// (POST /battles/{id}/scores)
	SubmitScores(c *gin.Context, id string)
	// Get balltes
	// (GET /events/{id}/battles)
	GetEventBattles(c *gin.Context, id string)
	// Health check
	// (GET /health)
	Health(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateBattle operation middleware
func (siw *ServerInterfaceWrapper) CreateBattle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateBattle(c)
}

// FinishBattle operation middleware
func (siw *ServerInterfaceWrapper) FinishBattle(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FinishBattle(c, id)
}

// SubmitScores operation middleware
func (siw *ServerInterfaceWrapper) SubmitScores(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitScores(c, id)
}

// GetEventBattles operation middleware
func (siw *ServerInterfaceWrapper) GetEventBattles(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEventBattles(c, id)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/battles", wrapper.CreateBattle)
	router.POST(options.BaseURL+"/battles/:id/finish", wrapper.FinishBattle)
	router.POST(options.BaseURL+"/battles/:id/scores", wrapper.SubmitScores)
	router.GET(options.BaseURL+"/events/:id/battles", wrapper.GetEventBattles)
	router.GET(options.BaseURL+"/health", wrapper.Health)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RXX2/bNhD/KgS3R6WWnWxL/NauXZftYUXzGAQBI55tZhKpkackRhBgyIC9bMCwb+IV",
	"DdAhC/YV6G80kJRkyXKXtnBcYHsxZPJ0f3+/u9MlTVSWKwkSDR1eUpNMIGP+8QlDTME95VrloFGAP+dM",
	"JqD7x4K7f3DBstyJUZZwiL+I+dZuspNs7YxivrXHd9lW//PB7s520o+3t7dpRHGaO2mDWsgxvYpKfYO1",
	"6YMzkLg2bevSY5Bh4fMHssjo8JDmILm7jKiQx7lWYw3G0IiOhBRmApweRQ27C+mO6nMhJegPjVgWacpO",
	"3BuoC+iov6pP1MkpJOgMBmS8BFOk2MXHib9dMzz6x6iQpccmUdpjspQTEmEMuomjewWrBB8z7/1I6cw9",
	"Uc4QtlBk8G71a9bp49fkmdZKd4sB1TEHk2iRo1CSDsMxQbhA0rxoAi5VCXOHRBii4YdCaOB0lSv15fCw",
	"NHfU8c/JCTlSXU8ev9gn9rW9nf9G5j/Zv+c/2pl9ZW/tjb2zb9zhtZ3Zu/nP9sa+sjN7O//V3s1/sX/Z",
	"N8T+YWfz6/m1vbUzd+C8E75llQg15PGLfRrRM9AmWOs/ih/FLl0qB8lyQYd02x9FNGc48SnrBQD751wZ",
	"7Pr8pQaGQBhxkBNyTMIb5ATwHEASPFckoNHx2ZXDZ3Kf1++WvTUkDww+UXzq7CRKIkhvkuV5KkIJeqfG",
	"2a268/+7JS8jrlIdNbPQCmE1HBdKHMf8gcmVNCGjg7jfrXuoGjFFkoAxoyJNpyTx9eQuyp14571q+KmG",
	"ER3ST3qLEdwr528v0Nk76n2oXHjmwiVSIRmpQpZm9x7MbB36U59OkhUGSc40ikTkjgNKplMiJFESKxYw",
	"JIZlQHwndf4NBpvyzwQHJ+wMSgISrVLwoDFFljE9XdA3uOvvKsr3LgW/6oXG3qR/m8Jf+fuawjnTLAN0",
	"ZB8efgC+hfPfdR/X+FnmhxWnywCNGhlaZsRRB7zx2jLemvUrEh/u0zYp6tH4wKyovbC/V6OA2Dt7435m",
	"9k/72o2RjWFQKuK3DmKKk0wgAidKe642Frwm7BaQDJCq7iKKbOzQVM0xetRFqTdl3o7SA+/EQZDqoLTt",
	"+f7T1jBt7QGbRfE6p2G9AtbB7EY0YxcicwtcP45oJmT5J/qXhbKrZ++99JwWfAwPM/1q1dFS1Mver3sG",
	"jhUGsG+M4qXhzY++b1yOCUs1MD4NQfPVLA6Sgf1Vdhxv/Y5S0raxXI5hxW75ErDQkqTCIFGj0o5xI9Zr",
	"6eyTzwH9TlB1iv/CPBIImXm3wUQX30JMazZ9O3KMz+lHhGsLKs/B7UtpimACRibAUpzcB4tBHJPvviVi",
	"RAzoM5GA+zpjqTiDDjC+DgpXl6Kt/GBZ11VEP7tH0AVWCrcCC2ZJMoHke5eXq38CAAD//6Gckn5iEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
