package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"user/internal/app"
	"user/internal/domain"
	"user/pkg/api/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.UserService.CreateUser(ctx, app.CreateUserParams{
		Name:  input.Name,
		Email: input.Email,
		Level: (*domain.DancerLevel)(input.Level),
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Name:      user.Name,
		Email:     user.Email,
		Level:     (*model.DancerLevel)(user.Level),
		CreatedAt: user.CreatedAt.Local().Format("2006-01-02 15:04:05"),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.UserService.FindUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Name:      user.Name,
		Email:     user.Email,
		Level:     (*model.DancerLevel)(user.Level),
		CreatedAt: user.CreatedAt.Local().Format("2006-01-02 15:04:05"),
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.ListUsres(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, 0, len(users))
	for _, u := range users {
		result = append(result, &model.User{
			ID:        u.ID,
			Name:      u.Name,
			Email:     u.Email,
			Level:     (*model.DancerLevel)(u.Level),
			CreatedAt: u.CreatedAt.Local().Format("2006-01-02 15:04:05"),
		})
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
